[font]
normal = { family = "Maple Mono Normal NF CN", style = "Regular" }
size = 14
offset = { x = 1, y = 4 }

[window]
decorations = "buttonless"
option_as_alt = "Both"

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[keyboard]
bindings = [
  { key = "I", mods = "Control", chars = "\u001b[105;5u" },
  { key = "Period", mods = "Control", chars = "\u001b[46;5u" },
  { key = "Comma", mods = "Control", chars = "\u001b[44;5u" },
  { key = "Semicolon", mods = "Control", chars = "\u001b[59;5u" },
]


[env]
TERM = "xterm-256color"
